version: '3'
services:
  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    restart: always
    ports:
      - 8081:80
    environment:
      - PMA_HOST=mysql-db
    depends_on:
      - mysql-db
    volumes:
      - phpmyadmin-volume:/etc/phpmyadmin/config.usr.inc.php

  mysql-db:
    image: mysql
    restart: always
    ports:
      - "3307:3306"
    environment:
      MYSQL_ROOT_PASSWORD: Bambademe99
      MYSQL_PASSWORD: Bambademe99
    volumes:
      - mysql-volume:/var/lib/mysql
volumes:
  mysql-volume:
  phpmyadmin-volume: